services:
  db:
    container_name: postgres
    image:  postgres:14.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./Docker:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    ports:
     - 8090:80

volumes:
  data-volume:
