services:
  db:
    image:  postgres:14.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./Docker:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  data-volume: